name: build-linux
on: [push]
jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run:  |
              sudo apt-get install python3-dev gcc cmake
              sudo apt-get update -y || true &&  DEBIAN_FRONTEND=noninteractive sudo apt-get install -y tzdata libx11-dev && sudo apt-get install -y --no-install-recommends libopencv-dev
              sudo apt-get install libraw-dev
              mkdir bin
              cd bin
              cmake ../.
              make
        name: upload_artifact
      - uses: actions/upload-artifact@v3
        with:
          name: artifact-linux-build
          path: |
                  bin
          retention-days: 1