name: build-linux
on: [push]
jobs:
  build-linux:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run:  |
              sudo apt-get install python3-dev gcc cmake
              sudo apt-get update -y || true &&  DEBIAN_FRONTEND=noninteractive sudo apt-get install -y tzdata libx11-dev && sudo apt-get install -y --no-install-recommends libopencv-dev
              sudo apt-get install libraw-dev
              mkdir bin
              cd bin
              cmake ../.
              make
        name: upload_artifact
      - uses: actions/upload-artifact@v3
        with:
          name: artifact-linux-build
          path: |
                  bin
          retention-days: 1

  hot-pixel-identification:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: [build-linux]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: |
            mkdir bin
              sudo apt-get update -y || true &&  DEBIAN_FRONTEND=noninteractive sudo apt-get install -y tzdata libx11-dev && sudo apt-get install -y --no-install-recommends libopencv-dev
              sudo apt-get install libraw-dev
      - uses: actions/download-artifact@v3
        with:
          name: artifact-linux-build
          path: bin/.
      - run:  |
              chmod u+x bin/tests
              ./bin/tests hot_pixel_identifier AstroPhotoStacker_test_files/data/CanonEOS6DMarkII_Andromeda/ temp_hot_pixel_file.txt AstroPhotoStacker_test_files/data/CanonEOS6DMarkII_Andromeda/reference_files/hot_pixels.txt
        name: hot-pixel-identification

  produce-alignment-file:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: [build-linux]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: |
            mkdir bin
              sudo apt-get update -y || true &&  DEBIAN_FRONTEND=noninteractive sudo apt-get install -y tzdata libx11-dev && sudo apt-get install -y --no-install-recommends libopencv-dev
              sudo apt-get install libraw-dev
      - uses: actions/download-artifact@v3
        with:
          name: artifact-linux-build
          path: bin/.
      - run:  |
              mkdir output
              chmod u+x bin/produce_alignment_file
              ./bin/produce_alignment_file -reference_file AstroPhotoStacker_test_files/data/CanonEOS6DMarkII_Andromeda/IMG_9132.CR2 -raw_files_dir AstroPhotoStacker_test_files/data/CanonEOS6DMarkII_Andromeda/ -alignment_file output/test_alignment.txt
      - uses: actions/upload-artifact@v3
        with:
          name: artifact-produce-alignment-file
          path: |
                  output/
          retention-days: 1

  validate-alignment-file:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: [produce-alignment-file]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - uses: actions/download-artifact@v3
        with:
          name: artifact-produce-alignment-file
          path: output/.
      - run: python3 CI_tests/python/compare_files.py output/test_alignment.txt AstroPhotoStacker_test_files/data/CanonEOS6DMarkII_Andromeda/reference_files/alignment.txt
        name: validate-alignment-file

  produce-stacked-image:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: [build-linux, produce-alignment-file]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: |
              sudo apt-get update -y || true &&  DEBIAN_FRONTEND=noninteractive sudo apt-get install -y tzdata libx11-dev && sudo apt-get install -y --no-install-recommends libopencv-dev
              sudo apt-get install libraw-dev
        name: install-dependencies
      - uses: actions/download-artifact@v3
        with:
          name: artifact-linux-build
          path: bin/.
      - uses: actions/download-artifact@v3
        with:
          name: artifact-produce-alignment-file
          path: output/.
      - run:  |
              chmod u+x bin/AstroPhotoStacker
              ./bin/AstroPhotoStacker -alignment_file output/test_alignment.txt -raw_files_dir AstroPhotoStacker_test_files/data/CanonEOS6DMarkII_Andromeda/ -output output/test_stacked_image_default_stack.png
      - uses: actions/upload-artifact@v3
        with:
          name: artifact-produce-stacked-image
          path: |
                  output/
          retention-days: 1